services:
  auth-service:
    build: .
    image: auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://shared-mongodb:27017/auth_service
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@shared-rabbitmq:5672/${RABBITMQ_VHOST}
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - auth-network
      - shared-infrastructure
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  auth-network:
    driver: bridge
  shared-infrastructure:
    external: true
    name: shared-infrastructure